apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: tic-tac-toe
data:
  BACKEND_URL: "http://backend.tic-tac-toe.svc.cluster.local:3001"
  app-config.js: |
    window.__APP_CONFIG__ = {
      backendUrl: "http://backend.tic-tac-toe.svc.cluster.local:3001"
    };
