apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tic-tac-toe
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 823963318980.dkr.ecr.ap-south-1.amazonaws.com/shaunak:backend-2333c239a31251558be02a46ebfd5a686c5698cf
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tic-tac-toe
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
